apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-board
  labels:
    app: simple-board
spec:
  selector:
    matchLables:
      app: simple-board
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-board
    spec:
      containers:
      - name: simple-board
        image: leesungkyu/boardwithk8s
        imagePullPolicy: Always
        volumeMounts:
        - name: log-volume
          mountPath: /log
        ports:
        - containerPort: 8070
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql_db:3306/simple_board?useSSL=false&allowPublicKeyRetrieval=true
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: 1234
      volumes:
        - name: log-volume
          emptyDir:
            {}