# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    #=============#
    # Master Node #
    #=============#
  
      config.vm.define "m-simple-board-k8s" do |cfg|
        cfg.vm.box = "sysnet4admin/CentOS-k8s"
        cfg.vm.provider "virtualbox" do |vb|
          vb.name = "m-simple-board-k8s"
          vb.cpus = 2
          vb.memory = 3072
          vb.customize ["modifyvm", :id, "--groups", "/k8s-SgMST-1.13.1(github_SysNet4Admin)"]
        end
        cfg.vm.host_name = "m-simple-board-k8s"
        cfg.vm.network "private_network", ip: "192.168.1.10"
        cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
        cfg.vm.provision "shell", path: "config.sh"
      end
  
    #==============#
    # Worker Nodes #
    #==============#
  
    config.vm.define "w-simple-board-k8s" do |cfg|
      cfg.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "w-simple-board-k8s"
        vb.cpus = 1
        vb.memory = 2560
        vb.customize ["modifyvm", :id, "--groups", "/k8s-SgMST-1.13.1(github_SysNet4Admin)"]
      end
      cfg.vm.host_name = "w-simple-board-k8s"
      cfg.vm.network "private_network", ip: "192.168.1.101"
      cfg.vm.network "forwarded_port", guest: 22, host: "60101", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "config.sh"
    end
  end