
### 로그인 api
POST {{host}}/login
Content-Type: application/json

## 아이디 및 비밀번호
{
  "userId": {{$random.email}},
  "userPw": {{$random.alphabetic()}}
}

### random 숫자는 각 요소에 맞는 기본키
### 게시글 조회 api
GET {{host}}/{{$random.integer()}}

### 게시글 목록 조회 api
GET {{host}}/post?page=1&size=10

### 게시글 수정 api
PUT {{host}}{{$random.integer()}}

### 게시글 등록 api
POST {{host}}/{{$random.integer()}}

### 게시글 삭제 api
DELETE {{host}}/{{$random.integer()}}

### 게시글 조회수 추가 api
GET {{host}}/{{$random.integer()}}/viewcnt