---
apiVersion: metallb.io/v1beta1 
kind: IPAddressPool
metadata:
  #해당 IPAddressPool 명과 사용하는 namespace
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.11-192.168.1.29
  autoAssign: true

--- 

apiVersion: metallb.io/v1beta1 
kind: L2Advertisement 
metadata:
  name: l2-network
  namespace: metallb-system
spec:
  ipAddressPools:
    - ip-pool